YunoHost-Apps/yeswiki_ynh

- check_process
- scripts/change_url
- Change_url don't fix
- Fix change_url script
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR5%20(plumf)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR5%20(plumf)/)
> Add change url

- LICENSE
- README.md
- README_fr.md
- conf/app.src
- conf/nginx.conf
- conf/php-fpm.conf
- manifest.json
- pull_request_template.md
- scripts/_common.sh
- scripts/backup
- scripts/change_url
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- *Broken app.src link*
- *Upgrade to Doryphore*
- *Upgrade to PHP7.3*
- *Update README*
- *Cleaning up scripts*
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR9%20(ericgaspar)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR9%20(ericgaspar)/)
> Update PHP7.3 + Doryphore version

- conf/app.src
- manifest.json
- scripts/install
- Installation impossible because there is an update version
- Just update to last version Doryphore as of November 23, 2020
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20(PR13)%20(plumf)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20(PR13)%20(plumf)/)
> Update to doryphore 23-10-2020

- LICENSE
- check_process
- conf/app.src
- manifest.json
- scripts/install
+ Add last version of YesWiki (Doryphore 2020-10-21)
+ Add html integration by defaut (issue #8)
+ Update license to YesWiki software
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR15%20(plumf)/)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR15%20(plumf)/)
> Update to doryphore 2020-10-21 & solved bug

- README.md
- README_fr.md
- check_process
- conf/app.src
- manifest.json
Update to Doryphore 2020-11-23-2
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR17%20(plumf)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR17%20(plumf)/)
> Update to Doryphore 2020-11-23-2

- README.md
- README_fr.md
- conf/app.src
- manifest.json
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- The weights for ynh_script_progression don't make sense #8 
- Update script
- Update to doryphore 2020-11-27-2
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR18%20(plumf)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR18%20(plumf)/)
> Update doryphore 2020-11-27-2 and solved bug

- README.md
- README_fr.md
- check_process
- conf/app.src
- manifest.json
- New version
- Update to doryphore 2020-11-30-4
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR19%20(plumf)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR19%20(plumf)/)
> Update to Doryphore 2020-11-30-4

- README.md
- README_fr.md
- conf/app.src
- manifest.json
- scripts/restore
- scripts/upgrade
Use a md5sum hash because it's provided in the YesWiki repository
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR-NUM-%20(USERNAME)/)
> Update to Doryphore 2021-04-06-2

- README.md
- README_fr.md
- check_process
- conf/app.src
- manifest.json
- scripts/_common.sh
- scripts/install
- scripts/restore
- scripts/upgrade
This update contains:
- Update to Doryphore 2021-04-06-2 #26 
- Add LDAP integration #20 
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*
> Update with tested changes

- README.md
- README_fr.md
- check_process
- conf/nginx.conf
- manifest.json
- pull_request_template.md
- scripts/change_url
- scripts/install
- scripts/restore
- scripts/upgrade
> Small fixes

- README.md
- README_fr.md
- check_process
- conf/app.src
- conf/nginx.conf
- manifest.json
- pull_request_template.md
- scripts/change_url
- scripts/install
- scripts/restore
- scripts/upgrade
Update to 2021-05-05-2 with added permission upgrades from #21 
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/yeswiki_ynh%20PR-NUM-%20(USERNAME)/)
> Update to 2021-05-05-2 with added permission upgrades

- README.md
- README_fr.md
- check_process
- conf/app.src
- manifest.json
- *New YesWiki version that supports geojson*
- *just release like the upstream!*
> New YesWiki version that supports geojson

- README.md
- README_fr.md
- manifest.json
> Fix linter

- README.md
- README_fr.md
- scripts/upgrade
> Keep ferme instances during upgrade

- tests.toml
> feat(tests): use more recent version

- README.md
- README_eu.md
- README_fr.md
- README_gl.md
- README_zh_Hans.md
- conf/nginx.conf
- manifest.toml
> fix mjs mimetypes

- conf/sudoers
- manifest.toml
- scripts/install
> WIP for CLIC

- conf/CLIC/default-content.sql
> fix(install): typo on {{rootPage}}

- README.md
- README_es.md
- README_eu.md
- README_fr.md
- README_gl.md
- README_zh_Hans.md
- manifest.toml
- bad sha for importer extension
- fixed sha by flabuse
> v4.4.4~ynh5

- README.md
- README_es.md
- README_eu.md
- README_fr.md
- README_gl.md
- README_zh_Hans.md
- manifest.toml
> v4.4.4~ynh6

- conf/sync_app_importer.sh
- scripts/install
> feat(yunohost extension): Add a post app install hook to update app list

- scripts/backup
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- [x ] Code finished and ready to be reviewed/tested
- [x ] The fix/enhancement were manually tested (if applicable)
> various small fixes

- scripts/upgrade
> Add yunohost_sso_domain config param during upgrade if it does not exists

- scripts/upgrade
> Fix upgrade error

- conf/sync_app_importer.sh
- conf/sync_user_importer.sh
- scripts/backup
- scripts/install
- scripts/remove
- scripts/upgrade
> add more importer hooks and change app importer data source name

- config_panel.toml
- manifest.toml
- scripts/_common.sh
- scripts/config
- scripts/install
- scripts/restore
- scripts/upgrade
- tests.toml
Add the feature to enable sftp access to the app, at install and later on with config panel
> Feat sftp panel

- README.md
- README_es.md
- README_eu.md
- README_fr.md
- README_gl.md
- README_id.md
- README_nl.md
- README_pl.md
- README_ru.md
- README_zh_Hans.md
- config_panel.toml
- manifest.toml
- scripts/_common.sh
- scripts/config
- scripts/install
- scripts/restore
- scripts/upgrade
- tests.toml
> sftp + upgrade to 4.5.2

- scripts/install
- scripts/upgrade
- the install dir belung to root instead of user
- chown one more time but at the end
> fix(install/upgrade): the install dir belung to root instead of user

- manifest.toml
> bump version
